config/routes.rb
Betmaker::Application.routes.draw do

  resources :sure_bets


  resources :posts


  get "main/index"

   root :to => 'main#index'


end

app/models/sure_bet.rb
class SureBet < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/sure_bets_controller.rb
class SureBetsController < ApplicationController
  # GET /sure_bets
  # GET /sure_bets.json
  def index
    @sure_bets = SureBet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sure_bets }
    end
  end

  # GET /sure_bets/1
  # GET /sure_bets/1.json
  def show
    @sure_bet = SureBet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sure_bet }
    end
  end

  # GET /sure_bets/new
  # GET /sure_bets/new.json
  def new
    @sure_bet = SureBet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sure_bet }
    end
  end

  # GET /sure_bets/1/edit
  def edit
    @sure_bet = SureBet.find(params[:id])
  end

  # POST /sure_bets
  # POST /sure_bets.json
  def create
    @sure_bet = SureBet.new(params[:sure_bet])

    respond_to do |format|
      if @sure_bet.save
        format.html { redirect_to @sure_bet, notice: 'Sure bet was successfully created.' }
        format.json { render json: @sure_bet, status: :created, location: @sure_bet }
      else
        format.html { render action: "new" }
        format.json { render json: @sure_bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sure_bets/1
  # PUT /sure_bets/1.json
  def update
    @sure_bet = SureBet.find(params[:id])

    respond_to do |format|
      if @sure_bet.update_attributes(params[:sure_bet])
        format.html { redirect_to @sure_bet, notice: 'Sure bet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sure_bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sure_bets/1
  # DELETE /sure_bets/1.json
  def destroy
    @sure_bet = SureBet.find(params[:id])
    @sure_bet.destroy

    respond_to do |format|
      format.html { redirect_to sure_bets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sure_bets_helper.rb
module SureBetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Betmaker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1 style ="background-color :#003366; color: antiquewhite; margin-top: 5px; margin-bottom: 5px;" class="text-center">Bet Maker</h1>

<div style="margin-top: 5%;" class="container">
  <div class="row">
    <div class="col text-center">
      <button class="btn btn-primary">Automate Betting</button>
    </div>
  </div>
<div style="margin-top: 10px; border-color: #003366; border-width: thick" >
  <div class="row" >
    <div class="col text-center">
      <button class="btn btn-danger">Place first Bet</button>
    </div>
  </div>
  <div class="row" style="margin-top: 10px">
    <div class="col text-center">
      <button class="btn btn-danger">Place second Bet</button>
    </div>
  </div>
</div>
</div>

app/views/sure_bets/_form.html.erb
<%= form_for(@sure_bet) do |f| %>
  <% if @sure_bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sure_bet.errors.count, "error") %> prohibited this sure_bet from being saved:</h2>

      <ul>
      <% @sure_bet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sure_bets/edit.html.erb
<h1>Editing sure_bet</h1>

<%= render 'form' %>

<%= link_to 'Show', @sure_bet %> |
<%= link_to 'Back', sure_bets_path %>

app/views/sure_bets/index.html.erb
<h1>Listing sure_bets</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sure_bets.each do |sure_bet| %>
  <tr>
    <td><%= link_to 'Show', sure_bet %></td>
    <td><%= link_to 'Edit', edit_sure_bet_path(sure_bet) %></td>
    <td><%= link_to 'Destroy', sure_bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sure bet', new_sure_bet_path %>

app/views/sure_bets/new.html.erb
<h1>New sure_bet</h1>

<%= render 'form' %>

<%= link_to 'Back', sure_bets_path %>

app/views/sure_bets/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sure_bet_path(@sure_bet) %> |
<%= link_to 'Back', sure_bets_path %>